name: Notify Teams on Commit or PR

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to Teams
        uses: actions/github-script@v6
        with:
          script: |
            const payload = context.payload;
            let message = "";
            if (context.eventName === "push") {
              const commit = payload.head_commit;
              message = `🚀 New commit pushed by ${commit.author.name}: **${commit.message}**
🔗 View Commit`;
            } else if (context.eventName === "pull_request") {
              const pr = payload.pull_request;
              message = `📣 Pull Request ${payload.action} by ${pr.user.login}: **${pr.title}**
🔗 View PR`;
            }
            const fetch = require('node-fetch');
            await fetch("https://penyardprojectconsultants.webhook.office.com/webhookb2/dc1f817a-1790-4791-8e33-0051400d5b49@a626b5ba-5c24-47cd-bdd4-863a794c0e67/IncomingWebhook/dfee146bf47641faac28ccb7dbb3914b/db5eb2f5-5243-42cf-8270-8c5bafb81ae7/V2PQXpY_2NzmofyjyKg-ma10ZmlczIuk74YZhB7YLIXfo1", {
              method: "POST",
              headers: {
                "Content-Type": "application/json"
              },
              body: JSON.stringify({
                text: message
              })
            });
